In [2]:
import numpy as np
from air_berlin import *

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [28]:
n = 5
x = basic_solved_state(1, n)
x = shuffle_along_axis(x, 1)
xvals = get_xvals(x)
X = random_large_discs(n)
A = adjacency_matrix(X)
P = shortest_path(A)
print("", X)
print(P)

 [3 1 3 2 2 3 4 3 3 2 4 4 2 1 1 4 1 2 2 2 4 1 1 1 3 1]
[[0 1 2 2 3 3 3 4 4 5 4 5 5 6 6 5 6 5 4 4 3 4 4 3 2 1]
 [1 0 1 1 2 2 2 3 3 4 3 4 4 5 5 4 5 4 3 3 2 3 3 2 1 2]
 [2 1 0 1 1 1 1 2 2 3 2 3 3 4 5 4 5 5 4 4 3 4 4 3 2 3]
 [1 2 1 0 1 2 2 2 3 3 3 3 4 5 5 4 5 5 5 5 4 5 5 4 3 2]
 [2 3 2 1 0 1 2 1 2 2 3 2 3 4 4 3 4 4 5 5 5 6 6 5 4 3]
 [2 2 1 1 1 0 1 2 1 2 2 3 3 4 5 4 5 5 5 5 4 5 5 4 3 3]
 [3 3 2 2 1 1 0 1 2 2 1 2 2 3 4 3 4 4 5 5 5 6 6 5 4 4]
 [4 4 3 3 2 2 1 0 1 1 2 1 2 3 3 2 3 3 4 4 4 5 6 6 5 5]
 [3 3 2 2 2 1 2 1 0 1 2 2 3 4 4 3 4 4 5 5 5 6 6 5 4 4]
 [4 4 3 3 3 2 2 2 1 0 1 2 2 3 4 3 4 4 5 5 5 6 7 6 5 5]
 [4 4 3 3 2 2 1 1 2 1 0 1 1 2 3 2 3 3 4 4 4 5 6 6 5 5]
 [4 4 3 3 3 2 2 2 1 1 1 0 1 2 2 1 2 2 3 3 3 4 5 6 5 5]
 [5 5 4 4 4 3 3 3 2 2 2 1 0 1 2 2 3 3 4 4 4 5 6 7 6 6]
 [6 6 5 5 4 4 3 3 3 3 2 2 1 0 1 2 3 3 4 4 4 5 6 7 6 7]
 [5 5 4 4 3 3 2 2 3 2 1 2 1 1 0 1 2 2 3 3 3 4 5 6 5 6]
 [5 5 4 4 4 3 3 3 2 2 2 1 2 2 1 0 1 1 2 2 2 3 4 5 4 5]
 [5 6 5 5 5 4 4 4 3 3 3 2 3 3 2 1 0 1 1 2 1 2 3 4 3 4]
 [6 7 6 6 

In [ ]:
x, xvals = expand(X, x, xvals)
print(x)

In [ ]:
h = AirBerlinDistanceHeuristic(n, X, 1)
h(X, x, xvals)

In [ ]:
a = np.arange(4*4).reshape(4, 4)
print(a)
a[np.arange(2).reshape(2, 1), np.arange(2).reshape(1, 2)]

In [ ]:
i = np.arange(4)
j = np.stack((i, (i + 2) % 4), axis=1)
print(j.flatten())
print(i.repeat(2))
A = np.arange(4*4).reshape(4, 4)
print(A)
A[i.repeat(2), j.flatten()]

In [ ]:
x = np.ones((4, 4, 4, 4))
y = np.zeros((7, 7))
x = x[:, np.newaxis, :, :, np.newaxis]
y = y[np.newaxis, :, np.newaxis, np.newaxis, :, np.newaxis]

print(x.shape, y.shape)
print((x * y).shape)

In [ ]:
(2, 3)[:-2]

In [ ]:


print("", X)
A = adjacency_matrix(X)
P = shortest_path(A)
print(A)
print(P)

In [ ]:
x = [[1, 1, 1, 2, 3, 0, 2, 2, 3, 3]]
d = x - np.roll(x, 1)
print(d < 0)

In [ ]:
D = mod_difference_matrix(5)
print(D)

In [ ]:
X = np.array([1, 2, 3, 1, 2, 3, 4, 1, 2, 3])
x = np.array([[1, 2, 3, 1, 2, 3, 0, 1, 2, 3]])
xvals = get_xvals(x)

In [ ]:
#x = x[2:3]
xvals = xvals[2:3]

In [ ]:
x, xvals = expand(X, x, xvals)
print(x.shape)
print(X)
print(x)

In [ ]:
n = 4
m = n*n + 1
x = basic_solved_state(1, n)
x = shuffle_along_axis(x, 1)

In [ ]:
expanded = Expanded()

In [241]:
for n in range(5, 16):
    print(16 - np.ceil(n / 2))

13.0
13.0
12.0
12.0
11.0
11.0
10.0
10.0
9.0
9.0
8.0


In [256]:
n = 7
#x = basic_solved_state(N=1, n=n)
#x = shuffle_along_axis(x, 1)
#X = random_large_discs(n, 1, 4)

#X[1] = 4
#print(x.shape, X.shape)

#X = np.array([int(val) for val in "1 2 3 2 3 2 1 2 1 2 1 3 4 1 2 3 4 1 2 3 1 2 3 2 3 4 1 2 1 2 1 2 3 4 1 2 3 4 1 2 3 1 2 3 1 2 3 1 2 3".split(" ")])
#x = np.array([[int(val) for val in "1 2 1 0 1 7 1 3 1 2 2 2 2 2 3 3 2 3 3 4 3 4 4 3 4 5 4 5 4 4 5 7 5 5 5 6 6 6 6 6 5 6 1 1 7 7 6 7 7 7".split(" ")]], dtype=x.dtype)
#print(x.shape, X.shape)

#n = 3
#x = np.array([[1, 1, 1, 3, 2, 2, 3, 3, 0, 2]], dtype=np.int8)
#X = np.array( [1, 2, 3, 4, 1, 2, 3, 1, 2, 3])

m = (n**2)

#heuristic1 = SolvedHeuristic(n)
heuristic1 = AirBerlinDistanceHeuristic(n, X, scale=1 / (n*n))
#heuristic = BreadthHeuristic(n, depth=3, h_breadth=HammingHeuristic(n))
heuristic2 = PairwiseDistanceHeuristic(n, scale=1 / (n*n))
#heuristic = BreadthHeuristic(n, depth=4, h_breadth=PairwiseDistanceHeuristic(n, scale=1 / (n*n)))
#heuristic1 = AdjacentDistanceHeuristic(n, 1)

print("Initial state:")
print("Large Disks:", X)
print("Small Disks:", x)

#path = ida_star(X, x, heuristic2)

#path = search(X, x, heuristic1, Fringe(), Expanded(), search_width=1, log_interval=1000, cost_scale=1)
print()
#path = search(X, x, heuristic2, Fringe(), Expanded(), search_width=1, log_interval=10000, cost_scale=1)
print()
#path = search(X, x, heuristic1, MinMaxFringe(maxsize=4096 * 4), Expanded(), search_width=1, log_interval=10000, cost_scale=1)
#path = search(X, x, heuristic1, BeamFringe(), Expanded(), search_width=2**10, log_interval=10, cost_scale=1)
path = search(X, x, heuristic2, BeamFringe(), Expanded(), search_width=2**10, log_interval=10, cost_scale=1)

#path = search(X, x, heuristic1, BeamFringe(), Expanded(), search_width=2**12, log_interval=10, cost_scale=1)
#path = search(X, x, heuristic2, BeamFringe(), Expanded(), search_width=2**18, log_interval=1, cost_scale=1)

#path = search(X, x, heuristic2, search_width=1, log_interval=1000, cost_scale=0)

#path = search(X, x, heuristic2, search_width=1, log_interval=1000, cost_scale=1)
#path = heuristic_search(X, x, heuristic, search_width=128, log_interval=5000)

Initial state:
Large Disks: [3 4 3 2 4 1 3 1 4 4 2 3 1 3 4 3 2 2 2 1 1 1 1 2 2 2 4 4 2 4 4 1 3 3 4 1 3
 1 1 1 3 3 1 1 2 4 4 3 2 4]
Small Disks: [[4 6 3 2 2 5 4 3 4 2 5 1 6 3 7 7 4 2 7 3 1 1 2 6 2 1 1 0 7 7 5 5 6 6 4 3
  3 7 5 6 1 5 4 5 6 1 7 2 3 4]]


Turn: 10, expanded: 2339, fringe: 0, time elapsed: 0.7457623481750488
Best g(x) + h(x) = 9 + 341.2200012207031
Turn: 20, expanded: 9313, fringe: 0, time elapsed: 2.9137840270996094
Best g(x) + h(x) = 19 + 338.0799865722656
Turn: 30, expanded: 15968, fringe: 0, time elapsed: 4.833757638931274
Best g(x) + h(x) = 29 + 334.45001220703125
Turn: 40, expanded: 22904, fringe: 0, time elapsed: 6.777987480163574
Best g(x) + h(x) = 39 + 330.57000732421875
Turn: 50, expanded: 30524, fringe: 0, time elapsed: 8.851295948028564
Best g(x) + h(x) = 49 + 324.94000244140625
Turn: 60, expanded: 38367, fringe: 0, time elapsed: 11.011605739593506
Best g(x) + h(x) = 59 + 318.3299865722656
Turn: 70, expanded: 45391, fringe: 0, time elapsed: 13.514864444732666
Be

In [ ]:
np.linspace(0, 1, 2)[:-1]

In [257]:
from ipywidgets import interact

ring_plot = RingPlot(n, cmap="gist_rainbow")

actions = get_actions(path)
hvals = heuristic1(X, path, get_xvals(path))

@interact(i=(0, path.shape[0]-1), t=(0.0, 1.0, 0.01))
def show_path(i, t):
    action = actions[i] if i != (path.shape[0]-1) else 0
    fig, ax = ring_plot.get_fig(X, path[i], action, hvals[i], i, t)
    plt.show()

interactive(children=(IntSlider(value=340, description='i', max=681), FloatSlider(value=0.5, description='t', …

In [ ]:
plt.close("all")
import gc
gc.collect()

In [ ]:
ring_plot = RingPlot(n, cmap="gist_rainbow")
hvals = heuristic(X, path, get_xvals(path))
ring_plot.save_frames(X, path, hvals, 5, "solutions/video/n9v2/", start_from=1100)

In [ ]:
import subprocess

name = "n9v1"
frames_path = f"/solutions/video/{name}/"
#os.chdir(os.getcwd())
#os.chdir(frames_path)
subprocess.call([
    'ffmpeg', '-framerate', '60', '-i', 'frame%02d.png', '-r', '60', '-pix_fmt', 'yuv720p',
    f'{name}.mp4'
])

In [ ]:
name = "n9v2.npy"
out = np.array([X, path], dtype=np.object)
np.save(f"solutions/{name}", out)

In [ ]:
name = "n9v2.npy"
load = np.load(f"solutions/{name}", allow_pickle=True)
X = load[0]
path = load[1]
n = int(np.sqrt(path.shape[1] - 1))

In [ ]:
# Test the Expanded class






In [ ]:
import torch
import time
import numpy as np

x = torch.randperm(10000000)

t = time.time()
torch.sort(x)
cpu_time = time.time() - t

print("cpu time", cpu_time)

x = x.cuda()

t = time.time()
torch.sort(x)
gpu_time = time.time() - t
print("gpu time", gpu_time)

print(f"gpu is {round(cpu_time / gpu_time, 1)} times faster than cpu")

In [ ]:
import torch

for row in list(torch.arange(4*4).reshape(4, 4)):
    row.byte()

In [13]:
#test_heuristic("PairwiseDistanceHeuristic(n, scale=1 / (n*n))")
#test_heuristic("AdjacentDistanceHeuristic(n, scale=1)")
#test_heuristic("HammingHeuristic(n)")
#test_heuristic("BreadthHeuristic(n, depth=7, h_breadth=HammingHeuristic(n))")
#test_heuristic("BreadthHeuristic(n, depth=4, h_breadth=PairwiseDistanceHeuristic(n, scale=1 / (n*n)))")
#test_heuristic("BreadthHeuristic(n, depth=3, h_breadth=AdjacentDistanceHeuristic(n, scale=1))")

test_heuristic("AirBerlinDistanceHeuristic(n, X, scale=1 / (n*n))")
#test_heuristic("BreadthHeuristic(n, depth=7, h_breadth=AirBerlinDistanceHeuristic(n, X, scale=1 / (n*n)))")

Heuristic is not admissible for state:
[2 3 1 1 1 2 2 0 3 3]
True cost to solution: 2 h(x): 2.444444444444444

Heuristic is not consistent for action:
[[2 0 1 3 1 2 1 2 3 3]
 [2 3 1 0 1 2 1 2 3 3]]
The heuristic decreased from 4.333333333333333 to 3.222222222222222

Heuristic is not consistent for action:
[[2 3 1 1 1 2 2 0 3 3]
 [0 3 1 1 1 2 2 2 3 3]]
The heuristic decreased from 2.444444444444444 to 0.6666666666666666

Heuristic is not admissible for state:
[3 1 1 1 2 0 2 3 3 2]
True cost to solution: 2 h(x): 2.333333333333333

Heuristic is not consistent for action:
[[3 1 1 1 2 0 2 3 3 2]
 [3 1 1 1 2 2 2 3 3 0]]
The heuristic decreased from 2.333333333333333 to 0.6666666666666666

Heuristic is not consistent for action:
[[2 3 0 3 1 1 3 1 2 2]
 [2 3 3 3 1 1 0 1 2 2]]
The heuristic decreased from 2.444444444444444 to 0.6666666666666666

Heuristic is not consistent for action:
[[2 2 3 0 3 1 1 2 1 3]
 [2 2 3 3 3 1 1 2 1 0]]
The heuristic decreased from 3.1111111111111107 to 1.88888888888

In [ ]:
path = "G:/Github Repositories/Ring-Sorting-AI/solutions/video/n9v1/"
files = os.listdir(path)

for file in files:
    num = int(file[5:-4])
    new_name = f"frame{num:06}.png"
    os.rename(path + file, path + new_name)
