In [1]:
import numpy as np
from air_berlin import *

%load_ext autoreload
%autoreload 2

In [ ]:
x = basic_solved_state(20, n)
x = shuffle_along_axis(x, 1)
x

In [ ]:
n = 3
x = basic_solved_state(1, n)
x = shuffle_along_axis(x, 1)
X = random_large_discs(n)
print(X)
print(x)

In [ ]:
x = action(0, X, x)
x

In [ ]:
n = 3
x = basic_solved_state(n)
np.random.shuffle(x)

print(x)

scale = 1 / (8 * (n - 1))
h = MaskedDistanceHeuristic(n=n, scale=scale)

print(h(x))

In [ ]:
max_int = np.iinfo(np.int64).max
min_int = np.iinfo(np.int64).min
big_ints = np.random.randint(low=min_int, high=max_int, size=10, dtype=np.int64)
big_ints

x = np.array([max_int], dtype=np.int64)

x // np.array([2])

In [ ]:
expanded = Expanded()

In [ ]:
len(normal_set)

In [15]:
# Test the Expanded class

from itertools import permutations

x = list(basic_solved_state(1, 3)[0])

normal_set = set()
expanded = Expanded()

iterations = 0
TP = 0
FP = 0
TN = 0
FN = 0

for p in permutations(x):
    iterations += 1
    
    x = np.array(p)[np.newaxis]
    
    if p in normal_set: 
        if expanded.contains(x)[0]:
            TN += 1
        else:
            FN += 1
    else:
        if not expanded.contains(x)[0]:
            TP += 1
        else:
            print(p)
            FP += 1
            
    normal_set.add(p)
    expanded.add(x)
    
    if iterations % 50000 == 0:
        print(f"iter={iterations} TN={TN}, FN={FN}, TP={TP}, FP={FP}")
        
    if iterations == 1000000:
        break


iter=50000 TN=49440, FN=0, TP=560, FP=0
iter=100000 TN=99440, FN=0, TP=560, FP=0
iter=150000 TN=148910, FN=0, TP=1090, FP=0
iter=200000 TN=198880, FN=0, TP=1120, FP=0
iter=250000 TN=248670, FN=0, TP=1330, FP=0
iter=300000 TN=298320, FN=0, TP=1680, FP=0
iter=350000 TN=348320, FN=0, TP=1680, FP=0
iter=400000 TN=397760, FN=0, TP=2240, FP=0
iter=450000 TN=446640, FN=0, TP=3360, FP=0
iter=500000 TN=495890, FN=0, TP=4110, FP=0
iter=550000 TN=544960, FN=0, TP=5040, FP=0
iter=600000 TN=594960, FN=0, TP=5040, FP=0
iter=650000 TN=643280, FN=0, TP=6720, FP=0
iter=700000 TN=693280, FN=0, TP=6720, FP=0
iter=750000 TN=743280, FN=0, TP=6720, FP=0
iter=800000 TN=793280, FN=0, TP=6720, FP=0
iter=850000 TN=843280, FN=0, TP=6720, FP=0
iter=900000 TN=893280, FN=0, TP=6720, FP=0
iter=950000 TN=943280, FN=0, TP=6720, FP=0
iter=1000000 TN=993280, FN=0, TP=6720, FP=0


In [ ]:
import math

for n in range(50):
    type(n*n + 1)
    possible_states = math.factorial(int(n*n + 1)) // (math.factorial(n) ** n)

In [301]:
n = 3
x = basic_solved_state(1, n)
x = shuffle_along_axis(x, 1)

print("Initial state:")
print(x)

X = random_large_discs(n)
h = MaskedDistanceHeuristic(n, scale=(1 / (8*(n-1))))
expanded = Expanded()
expanded.add(x)

search_width = 4

for i in range(100):
    x = expand(X, x)
    backtracked = expanded.contains(x)
    x = x[~backtracked]
    expanded.add(x)
    
    hvals = h(x)
    arg_best = hvals.argsort()
    arg_best = arg_best[:min(search_width, arg_best.shape[0])]
    
    x = x[arg_best]
    hvals = hvals[arg_best]
    
    print()
    print("h(x):\n", hvals)
    print("Nodes:")
    print(x)
    if hvals[0] < 1e-2:
        print("Done")
        break

Initial state:
[[2 3 1 0 2 3 1 1 3 2]]

h(x):
 [2.5   2.875 3.125 3.125]
Nodes:
[[0 3 1 2 2 3 1 1 3 2]
 [2 3 0 1 2 3 1 1 3 2]
 [2 3 1 2 0 3 1 1 3 2]
 [2 3 1 1 2 3 0 1 3 2]]

h(x):
 [2.    2.375 2.5   2.625]
Nodes:
[[2 3 1 2 2 3 1 1 3 0]
 [2 3 1 1 2 3 2 1 3 0]
 [2 0 1 2 3 3 1 1 3 2]
 [2 0 3 1 2 3 1 1 3 2]]

h(x):
 [2.125 2.25  2.25  2.25 ]
Nodes:
[[0 3 1 1 2 3 2 1 3 2]
 [2 3 1 2 2 3 1 1 0 3]
 [0 2 1 2 3 3 1 1 3 2]
 [2 3 3 1 2 3 1 1 0 2]]

h(x):
 [1.125 2.    2.375 2.375]
Nodes:
[[2 2 1 2 3 3 1 1 3 0]
 [2 3 3 1 2 3 1 1 2 0]
 [3 0 1 1 2 3 2 1 3 2]
 [2 3 1 2 2 3 1 0 1 3]]

h(x):
 [1.375 1.375 1.375 1.75 ]
Nodes:
[[2 2 1 2 3 3 1 1 0 3]
 [2 2 1 2 3 0 1 1 3 3]
 [0 3 3 1 2 3 1 1 2 2]
 [2 3 3 0 2 3 1 1 2 1]]

h(x):
 [0.75  1.125 1.125 1.25 ]
Nodes:
[[2 2 0 2 3 1 1 1 3 3]
 [2 2 1 2 0 3 1 1 3 3]
 [0 3 3 2 2 3 1 1 2 1]
 [2 2 1 2 3 1 0 1 3 3]]

h(x):
 [0.625 0.75  0.75  0.875]
Nodes:
[[2 2 2 0 3 1 1 1 3 3]
 [2 0 2 2 3 1 1 1 3 3]
 [2 2 1 2 1 3 1 0 3 3]
 [2 2 1 2 3 1 3 1 3 0]]

h(x):
 [0.625 0.625 0.

In [207]:
x = np.arange(16).reshape(4, 4)
print(x)
#np.take_along_axis(x, np.array([(1,0, 1, 0)]), axis=0)
ids = np.array([0, 1, 2, 3])

x[ids, range(4)]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 0,  5, 10, 15])

In [153]:
x[...,].shape

SyntaxError: invalid syntax (<ipython-input-153-a922494e8975>, line 1)