In [1]:
import numpy as np
from air_berlin import *
from visualizations import *

%load_ext autoreload
%autoreload 2

In [6]:
n = 3
x = basic_solved_state(1, n)
#x = shuffle_along_axis(x, 1)
X = random_large_discs(n)
print(X)
print(x)

[4 4 1 4 4 2 2 3 4 2]
[[0 1 1 1 2 2 2 3 3 3]]


In [ ]:
n = 3
x = basic_solved_state(1, n)
x = shuffle_along_axis(x, 1)
a = all_solved_states(n)

x = np.expand_dims(x, 1)
a = np.expand_dims(a, 0)
print(a.shape)
print(x.shape)

In [ ]:
print(a)
print(x)
E = (a == x) * 1

print(E)
print(E.sum(axis=2))

In [ ]:
cw_actual = clockwise_distance(x.reshape(n*n, 1), x.reshape(1, n*n), n)
print(cw_actual)

In [ ]:
cw_target = clockwise_distance_matrix(n*n) / n
#cw_target += np.sign(cw_target) - 1e-3
#cw_target = np.trunc(cw_target).astype(np.int32)
print(cw_target)

In [ ]:
clockwise_distance(cw_actual, cw_target, n)

In [ ]:
distance_matrix(10)

In [ ]:
set([1, 1, 1, 3, 3, 3, 4, 4])

In [ ]:
np.trunc(signed_distance_matrix(10) / 3).astype(np.int32)

In [ ]:
n = 3
x = basic_solved_state(n)
np.random.shuffle(x)

print(x)

scale = 1 / (8 * (n - 1))
h = MaskedDistanceHeuristic(n=n, scale=scale)

print(h(x))

In [ ]:
expanded = Expanded()

In [ ]:
# Test the Expanded class

from itertools import permutations

x = list(basic_solved_state(1, 3)[0])

normal_set = set()
expanded = Expanded()

iterations = 0
TP = 0
FP = 0
TN = 0
FN = 0

for p in permutations(x):
    iterations += 1
    
    x = np.array(p)[np.newaxis]
    
    if p in normal_set: 
        if expanded.contains(x)[0]:
            TN += 1
        else:
            FN += 1
    else:
        if not expanded.contains(x)[0]:
            TP += 1
        else:
            print(p)
            FP += 1
            
    normal_set.add(p)
    expanded.add(x)
    
    if iterations % 50000 == 0:
        print(f"iter={iterations} TN={TN}, FN={FN}, TP={TP}, FP={FP}")
        
    if iterations == 1000000:
        break


In [5]:
n = 3
x = basic_solved_state(1, n)
x = shuffle_along_axis(x, 1)
X = random_large_discs(n)

print("Initial state:")
print("Large Disks:", X)
print("Small Disks:", x)

h = AscendingMaskedDistanceHeuristic(n, scale=(1 / (8*(n-1))))
#h = AscendingDistanceHeuristic(n, scale=1)
#h = TestAllHeuristic(n)
expanded = Expanded()
expanded.add(x, x_parent=None)

search_width = 32
verbose = False

for i in range(100000):
    x, x_parent = expand(X, x)
    backtracked = expanded.contains(x)
    x = x[~backtracked]
    x_parent = x_parent[~backtracked]
    
    hvals = h(x)
    arg_best = hvals.argsort()
    arg_best = arg_best[:min(search_width, arg_best.shape[0])]
    
    x = x[arg_best]
    hvals = hvals[arg_best]
    x_parent = x_parent[arg_best]
    break
    expanded.add(x, x_parent)
    if i % 250 == 0:
        print(hvals[0])
        
    if verbose:
        print()
        print("h(x):\n", hvals)
        print("Nodes:")
        print(x)
    
    if hvals[0] < 1e-7:
        print("Done.")
        path = expanded.path_to_root(x[:1], max_depth=i*20)
        if verbose:
            print("Large Disks:")
            print(X)
            print("Solution")
            print(path)
        break

Initial state:
Large Disks: [4 4 3 3 4 1 2 1 1 3]
Small Disks: [[1 1 2 3 1 3 2 2 3 0]]
[[0 1 2 3 1 3 2 2 3 1]
 [1 1 2 3 1 3 2 2 0 3]
 [1 1 0 3 1 3 2 2 3 2]
 [1 1 2 3 1 3 0 2 3 2]]
[[0 1 2 3 1 3 2 2 3 1]
 [0 3 1 1 2 3 1 3 2 2]
 [0 3 1 3 2 2 3 2 1 1]
 [0 2 3 2 1 1 2 3 1 3]]
[0 1 1 1 2 2 2 3 3 3]
[[0 0 1 2 1 1 0 1 0 2]
 [0 2 0 0 0 1 1 0 1 1]
 [0 2 0 2 0 0 1 1 2 2]
 [0 1 2 1 1 1 0 0 2 0]]
2.5625 0.5


In [ ]:
x[...,].shape

In [ ]:
# list gives you a view of rows
y = np.arange(16).reshape((4, 4))
#list(y)[0][0] = 100
list(y)

In [ ]:
y = np.arange(5)
list(y)[0] = 100
list(y)

In [ ]:
t = np.tile(np.arange(10), reps=3).reshape(3, 10)
r = np.array([-2, 2, -5])
asdf = [np.roll(ti, ri) for ti, ri in zip(list(t), r)]
print(asdf)


In [ ]:
ring_plot = RingPlot(n, cmap="rainbow")

In [ ]:
from ipywidgets import interact

@interact(i=(0, path.shape[0]-1))
def show_path(i):
    ring_plot.show(path[i])