In [154]:
import numpy as np
from air_berlin import *
from visualizations import *

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [267]:
n = 3
x = basic_solved_state(1, n)
x = shuffle_along_axis(x, 1)
X = random_large_discs(n)
print(X)
print(x)

[4 3 3 2 3 1 3 2 1 4]
[[3 1 0 3 3 1 2 1 2 2]]


In [279]:
x, _ = expand(X, x)
print(x.shape)

(3864260, 10)


In [179]:
n = 4
m = n*n + 1
x = basic_solved_state(1, n)
x = shuffle_along_axis(x, 1)
#a = all_solved_states(n)

#x = np.expand_dims(x, 1)
#a = np.expand_dims(a, 0)
#print(a.shape)
print(x.shape)

(1, 17)


In [174]:
# filter 0
x = x[x != 0].reshape(n*n) - 1
print(x)

[1 3 1 2 3 1 2 3 0 3 0 0 2 2 0 1]


In [182]:
print(x)
print(np.minimum(n*n + 1 - x, x))

[[1 2 2 4 3 4 2 2 4 0 1 1 3 3 1 4 3]]
[[1 2 2 4 3 4 2 2 4 0 1 1 3 3 1 4 3]]


In [176]:
print(x)
cw_actual = (np.expand_dims(x, -2) - np.expand_dims(x, -1)) % n
cw_actual *= n
print(cw_actual)

[1 3 1 2 3 1 2 3 0 3 0 0 2 2 0 1]
[[ 0  8  0  4  8  0  4  8 12  8 12 12  4  4 12  0]
 [ 8  0  8 12  0  8 12  0  4  0  4  4 12 12  4  8]
 [ 0  8  0  4  8  0  4  8 12  8 12 12  4  4 12  0]
 [12  4 12  0  4 12  0  4  8  4  8  8  0  0  8 12]
 [ 8  0  8 12  0  8 12  0  4  0  4  4 12 12  4  8]
 [ 0  8  0  4  8  0  4  8 12  8 12 12  4  4 12  0]
 [12  4 12  0  4 12  0  4  8  4  8  8  0  0  8 12]
 [ 8  0  8 12  0  8 12  0  4  0  4  4 12 12  4  8]
 [ 4 12  4  8 12  4  8 12  0 12  0  0  8  8  0  4]
 [ 8  0  8 12  0  8 12  0  4  0  4  4 12 12  4  8]
 [ 4 12  4  8 12  4  8 12  0 12  0  0  8  8  0  4]
 [ 4 12  4  8 12  4  8 12  0 12  0  0  8  8  0  4]
 [12  4 12  0  4 12  0  4  8  4  8  8  0  0  8 12]
 [12  4 12  0  4 12  0  4  8  4  8  8  0  0  8 12]
 [ 4 12  4  8 12  4  8 12  0 12  0  0  8  8  0  4]
 [ 0  8  0  4  8  0  4  8 12  8 12 12  4  4 12  0]]


In [177]:
diff = (cw_actual - ring_matrix(n*n)) % (n*n)
diff = np.minimum(n*n - np.abs(diff), np.abs(diff))
print(diff)

[[0 7 2 1 4 5 2 1 4 1 2 1 8 7 2 1]
 [7 0 7 6 3 4 7 6 3 8 5 6 1 0 7 6]
 [2 7 0 3 6 3 0 3 6 1 4 3 6 7 0 3]
 [1 6 3 0 3 6 3 0 3 2 1 0 7 6 3 0]
 [4 3 6 3 0 7 6 3 0 5 2 3 4 3 6 3]
 [5 4 3 6 7 0 3 6 7 4 7 6 3 4 3 6]
 [2 7 0 3 6 3 0 3 6 1 4 3 6 7 0 3]
 [1 6 3 0 3 6 3 0 3 2 1 0 7 6 3 0]
 [4 3 6 3 0 7 6 3 0 5 2 3 4 3 6 3]
 [1 8 1 2 5 4 1 2 5 0 3 2 7 8 1 2]
 [2 5 4 1 2 7 4 1 2 3 0 1 6 5 4 1]
 [1 6 3 0 3 6 3 0 3 2 1 0 7 6 3 0]
 [8 1 6 7 4 3 6 7 4 7 6 7 0 1 6 7]
 [7 0 7 6 3 4 7 6 3 8 5 6 1 0 7 6]
 [2 7 0 3 6 3 0 3 6 1 4 3 6 7 0 3]
 [1 6 3 0 3 6 3 0 3 2 1 0 7 6 3 0]]


In [87]:
new_h = (cw_actual - cw_dists) % m
#new_h = np.abs(np.maximum(new_h - n, 0))
print(new_h)

[[[ 0  3  2  1  0  3  2  1  0  3  2  1  0  3  2  1  0]
  [ 0  0 16 15 14  0 16 15 14  0 16 15 14  0 16 15 14]
  [ 1  1  0 16 15  1  0 16 15  1  0 16 15  1  0 16 15]
  [ 2  2  1  0 16  2  1  0 16  2  1  0 16  2  1  0 16]
  [ 3  3  2  1  0  3  2  1  0  3  2  1  0  3  2  1  0]
  [ 0  3  2  1  0  0 16 15 14  0 16 15 14  0 16 15 14]
  [ 1  4  3  2  1  1  0 16 15  1  0 16 15  1  0 16 15]
  [ 2  5  4  3  2  2  1  0 16  2  1  0 16  2  1  0 16]
  [ 3  6  5  4  3  3  2  1  0  3  2  1  0  3  2  1  0]
  [ 0  3  2  1  0  3  2  1  0  0 16 15 14  0 16 15 14]
  [ 1  4  3  2  1  4  3  2  1  1  0 16 15  1  0 16 15]
  [ 2  5  4  3  2  5  4  3  2  2  1  0 16  2  1  0 16]
  [ 3  6  5  4  3  6  5  4  3  3  2  1  0  3  2  1  0]
  [ 0  3  2  1  0  3  2  1  0  3  2  1  0  0 16 15 14]
  [ 1  4  3  2  1  4  3  2  1  4  3  2  1  1  0 16 15]
  [ 2  5  4  3  2  5  4  3  2  5  4  3  2  2  1  0 16]
  [ 3  6  5  4  3  6  5  4  3  6  5  4  3  3  2  1  0]]]


In [67]:
cw_target = clockwise_distance_matrix(n*n) / n
cw_target += np.sign(cw_target) - 1e-3
cw_target = np.trunc(cw_target).astype(np.int32)
print(cw_target)

[[ 0  1  1  1  1  2  2  2 -3 -2 -2 -2 -2 -1 -1 -1]
 [-1  0  1  1  1  1  2  2  2 -3 -2 -2 -2 -2 -1 -1]
 [-1 -1  0  1  1  1  1  2  2  2 -3 -2 -2 -2 -2 -1]
 [-1 -1 -1  0  1  1  1  1  2  2  2 -3 -2 -2 -2 -2]
 [-2 -1 -1 -1  0  1  1  1  1  2  2  2 -3 -2 -2 -2]
 [-2 -2 -1 -1 -1  0  1  1  1  1  2  2  2 -3 -2 -2]
 [-2 -2 -2 -1 -1 -1  0  1  1  1  1  2  2  2 -3 -2]
 [-2 -2 -2 -2 -1 -1 -1  0  1  1  1  1  2  2  2 -3]
 [-3 -2 -2 -2 -2 -1 -1 -1  0  1  1  1  1  2  2  2]
 [ 2 -3 -2 -2 -2 -2 -1 -1 -1  0  1  1  1  1  2  2]
 [ 2  2 -3 -2 -2 -2 -2 -1 -1 -1  0  1  1  1  1  2]
 [ 2  2  2 -3 -2 -2 -2 -2 -1 -1 -1  0  1  1  1  1]
 [ 1  2  2  2 -3 -2 -2 -2 -2 -1 -1 -1  0  1  1  1]
 [ 1  1  2  2  2 -3 -2 -2 -2 -2 -1 -1 -1  0  1  1]
 [ 1  1  1  2  2  2 -3 -2 -2 -2 -2 -1 -1 -1  0  1]
 [ 1  1  1  1  2  2  2 -3 -2 -2 -2 -2 -1 -1 -1  0]]


In [69]:
clockwise_distance(cw_actual, cw_target, n)

ValueError: operands could not be broadcast together with shapes (16,16) (17,17) 

In [68]:
clockwise_distance_matrix(n*n + 1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8, -8, -7, -6, -5, -4, -3, -2,
        -1],
       [-1,  0,  1,  2,  3,  4,  5,  6,  7,  8, -8, -7, -6, -5, -4, -3,
        -2],
       [-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8, -8, -7, -6, -5, -4,
        -3],
       [-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8, -8, -7, -6, -5,
        -4],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8, -8, -7, -6,
        -5],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8, -8, -7,
        -6],
       [-6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8, -8,
        -7],
       [-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,
        -8],
       [-8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,
         8],
       [ 8, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,
         7],
       [ 7,  8, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,
         6],
       [ 6,  7,  8, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  

In [ ]:
set([1, 1, 1, 3, 3, 3, 4, 4])

In [ ]:
np.trunc(signed_distance_matrix(10) / 3).astype(np.int32)

In [ ]:
n = 3
x = basic_solved_state(n)
np.random.shuffle(x)

print(x)

scale = 1 / (8 * (n - 1))
h = MaskedDistanceHeuristic(n=n, scale=scale)

print(h(x))

In [ ]:
expanded = Expanded()

In [ ]:
# Test the Expanded class

from itertools import permutations

x = list(basic_solved_state(1, 3)[0])

normal_set = set()
expanded = Expanded()

iterations = 0
TP = 0
FP = 0
TN = 0
FN = 0

for p in permutations(x):
    iterations += 1
    
    x = np.array(p)[np.newaxis]
    
    if p in normal_set: 
        if expanded.contains(x)[0]:
            TN += 1
        else:
            FN += 1
    else:
        if not expanded.contains(x)[0]:
            TP += 1
        else:
            print(p)
            FP += 1
            
    normal_set.add(p)
    expanded.add(x)
    
    if iterations % 50000 == 0:
        print(f"iter={iterations} TN={TN}, FN={FN}, TP={TP}, FP={FP}")
        
    if iterations == 1000000:
        break


In [227]:
n = 25
x = basic_solved_state(1, n)
x = shuffle_along_axis(x, 1)
X = random_large_discs(n)

print("Initial state:")
print("Large Disks:", X)
print("Small Disks:", x)

h = YetAnotherAscendingDistanceHeuristic(n, weak_zero=True)
#h = AscendingMaskedDistanceHeuristic(n, scale=(1 / (8*(n-1))))
#h = AscendingDistanceHeuristic(n, scale=1)
#h = TestAllHeuristic(n)
expanded = Expanded()
expanded.add(x, x_parent=None)

search_width = 32
verbose = False

for i in range(100000):
    x, x_parent = expand(X, x)
    backtracked = expanded.contains(x)
    x = x[~backtracked]
    x_parent = x_parent[~backtracked]
    
    hvals = h(x)
    arg_best = hvals.argsort()
    arg_best = arg_best[:min(search_width, arg_best.shape[0])]
    
    x = x[arg_best]
    hvals = hvals[arg_best]
    x_parent = x_parent[arg_best]
    expanded.add(x, x_parent)
    if i % 250 == 0:
        print(hvals[0])

        
    if verbose:
        print()
        print("h(x):\n", hvals)
        print("Nodes:")
        print(x)
    
    if hvals[0] < 1e-7:
        print("Done.")
        path = expanded.path_to_root(x[:1], max_depth=i*20)
        if verbose:
            print("Large Disks:")
            print(X)
            print("Solution")
            print(path)
        break

Initial state:
Large Disks: [4 2 3 2 4 3 1 1 4 2 1 2 2 3 1 3 1 4 4 1 3 2 3 3 4 3 3 2 4 4 2 3 1 3 1 4 3
 4 2 2 4 4 3 1 1 2 2 3 2 4 1 2 4 3 3 2 3 1 3 1 3 1 3 1 3 1 1 2 1 4 4 2 1 3
 2 4 4 3 3 1 2 2 4 1 1 3 2 2 2 3 4 3 3 2 2 3 2 1 2 1 3 1 2 4 4 2 3 3 1 1 3
 3 3 4 4 1 3 3 3 1 3 1 1 4 2 2 1 4 3 4 2 1 3 1 1 1 3 2 4 4 2 2 2 2 2 3 1 1
 3 2 4 1 1 4 1 4 3 2 1 1 3 2 4 1 1 1 3 2 3 1 1 1 2 3 4 1 3 3 4 4 4 3 4 3 2
 4 3 3 2 4 3 4 2 1 3 1 2 1 3 4 2 1 3 2 4 2 1 1 2 4 1 4 3 2 1 3 2 3 4 1 1 3
 2 4 4 2 4 3 3 2 1 3 2 2 2 3 4 2 1 4 4 2 1 2 2 2 2 2 3 1 3 3 2 1 3 3 2 4 2
 3 2 2 3 1 3 3 1 4 2 1 1 2 3 4 3 2 1 3 1 2 4 3 4 2 4 4 3 4 4 1 4 4 3 2 4 4
 3 3 2 4 1 2 3 1 2 1 1 1 3 1 3 1 1 3 3 1 1 4 2 4 4 1 3 2 4 2 1 4 1 2 4 3 3
 3 4 1 3 4 3 2 1 2 1 4 4 3 4 1 4 1 4 1 3 4 4 1 3 1 2 3 4 2 3 3 4 2 3 4 3 4
 4 3 3 4 1 4 3 1 2 4 2 4 2 4 2 4 3 4 1 3 3 3 1 2 3 1 1 3 1 2 2 3 3 2 1 3 1
 2 3 2 3 4 3 4 2 2 3 4 1 2 2 3 1 3 2 1 2 3 3 1 1 2 2 3 2 4 2 3 2 2 3 3 1 2
 1 2 1 2 3 3 2 1 1 2 1 1 2 2 3 1 2 4 1 2 4 1 2 4 1 4 1 1 4 2 2 3 1 1 1 4

MemoryError: Unable to allocate 106. MiB for an array with shape (71, 625, 625) and data type int32

In [ ]:
x[...,].shape

In [ ]:
# list gives you a view of rows
y = np.arange(16).reshape((4, 4))
#list(y)[0][0] = 100
list(y)

In [ ]:
y = np.arange(5)
list(y)[0] = 100
list(y)

In [ ]:
t = np.tile(np.arange(10), reps=3).reshape(3, 10)
r = np.array([-2, 2, -5])
asdf = [np.roll(ti, ri) for ti, ri in zip(list(t), r)]
print(asdf)


In [234]:
n = 15
ring_plot = RingPlot(n, cmap="rainbow")

In [258]:
from ipywidgets import interact

@interact(i=(0, path.shape[0]-1))
def show_path(i):
    ring_plot.show(path[i])

interactive(children=(IntSlider(value=10433, description='i', max=20867), Output()), _dom_classes=('widget-int…

In [226]:
name = "n15v1.npy"
out = np.array([X, path], dtype=np.object)
#np.save(f"solutions/{name}", out)

In [230]:
name = "n15v1.npy"
load = np.load(f"solutions/{name}", allow_pickle=True)
X = load[0]
path = load[1]

In [254]:
hash(np.arange(28).tobytes())

-8828175566804271049

In [257]:
np.array([np.nan], dtype=np.int64)

ValueError: cannot convert float NaN to integer

In [7]:
import torch
import time
import numpy as np

x = torch.randperm(10000000)

t = time.time()
torch.sort(x)
cpu_time = time.time() - t

print("cpu time", cpu_time)

x = x.cuda()

t = time.time()
torch.sort(x)
gpu_time = time.time() - t
print("gpu time", gpu_time)

print(f"gpu is {round(cpu_time / gpu_time, 1)} times faster than cpu")

cpu time 1.2695953845977783
gpu time 0.05198383331298828
gpu is 24.4 times faster than cpu
