In [1]:
import numpy as np
from air_berlin import *

%load_ext autoreload
%autoreload 2

In [ ]:
x = basic_solved_state(20, n)
x = shuffle_along_axis(x, 1)
x

In [ ]:
n = 3
x = basic_solved_state(1, n)
x = shuffle_along_axis(x, 1)
X = random_large_discs(n)
print(X)
print(x)

In [ ]:
x = action(0, X, x)
x

In [ ]:
n = 3
x = basic_solved_state(n)
np.random.shuffle(x)

print(x)

scale = 1 / (8 * (n - 1))
h = MaskedDistanceHeuristic(n=n, scale=scale)

print(h(x))

In [ ]:
max_int = np.iinfo(np.int64).max
min_int = np.iinfo(np.int64).min
big_ints = np.random.randint(low=min_int, high=max_int, size=10, dtype=np.int64)
big_ints

x = np.array([max_int], dtype=np.int64)

x // np.array([2])

In [ ]:
expanded = Expanded()

In [ ]:
len(normal_set)

In [2]:
# Test the Expanded class

from itertools import permutations

x = list(basic_solved_state(1, 3)[0])

normal_set = set()
expanded = Expanded()

iterations = 0
TP = 0
FP = 0
TN = 0
FN = 0

for p in permutations(x):
    iterations += 1
    
    x = np.array(p)[np.newaxis]
    
    if p in normal_set: 
        if expanded.contains(x)[0]:
            TN += 1
        else:
            FN += 1
    else:
        if not expanded.contains(x)[0]:
            TP += 1
        else:
            print(p)
            FP += 1
            
    normal_set.add(p)
    expanded.add(x)
    
    if iterations % 50000 == 0:
        print(f"iter={iterations} TN={TN}, FN={FN}, TP={TP}, FP={FP}")
        
    if iterations == 1000000:
        break


TypeError: add() missing 1 required positional argument: 'x_parent'

In [10]:
n = 3
x = basic_solved_state(1, n)
x = shuffle_along_axis(x, 1)
X = random_large_discs(n)

print("Initial state:")
print("Large Disks:", X)
print("Small Disks:", x)

h = MaskedDistanceHeuristic(n, scale=(1 / (8*(n-1))))
expanded = Expanded()
expanded.add(x, x_parent=None)

search_width = 4

for i in range(100):
    x, x_parent = expand(X, x)
    backtracked = expanded.contains(x)
    x = x[~backtracked]
    x_parent = x_parent[~backtracked]
    expanded.add(x, x_parent)
    
    hvals = h(x)
    arg_best = hvals.argsort()
    arg_best = arg_best[:min(search_width, arg_best.shape[0])]
    
    x = x[arg_best]
    hvals = hvals[arg_best]
    
    print()
    print("h(x):\n", hvals)
    print("Nodes:")
    print(x)
    if hvals[0] < 1e-2:
        print("Done.")
        print("Large Disks:")
        print(X)
        path = expanded.path_to_root(x[:1])
        print("Solution")
        print(path)
        break

Initial state:
Large Disks: [1 2 4 1 4 2 2 3 2 4]
Small Disks: [[1 2 3 1 3 1 2 2 3 0]]

h(x):
 [2.375 2.375 3.125 3.125]
Nodes:
[[0 2 3 1 3 1 2 2 3 1]
 [1 2 3 1 3 1 2 2 0 3]
 [1 2 3 0 3 1 2 2 3 1]
 [1 2 3 1 3 0 2 2 3 1]]

h(x):
 [2.375 2.5   2.625 2.625]
Nodes:
[[0 2 3 1 3 1 2 2 1 3]
 [1 2 3 1 3 1 2 0 2 3]
 [2 0 3 1 3 1 2 2 3 1]
 [1 2 3 1 3 1 0 2 2 3]]

h(x):
 [1.625 2.125 2.25  2.5  ]
Nodes:
[[3 2 3 1 3 1 2 2 1 0]
 [2 1 3 1 3 1 2 2 3 0]
 [0 2 3 1 3 1 2 1 2 3]
 [1 2 3 1 0 1 2 3 2 3]]

h(x):
 [1.125 1.5   1.5   1.875]
Nodes:
[[0 1 3 1 3 1 2 2 3 2]
 [3 2 3 0 3 1 2 2 1 1]
 [3 2 3 1 3 1 2 1 2 0]
 [3 2 3 1 3 1 2 2 0 1]]

h(x):
 [1.375 1.375 1.5   1.625]
Nodes:
[[1 0 3 1 3 1 2 2 3 2]
 [3 2 3 3 0 1 2 2 1 1]
 [3 2 3 0 3 1 2 1 2 1]
 [3 2 0 3 3 1 2 2 1 1]]

h(x):
 [1.25  1.375 1.375 1.5  ]
Nodes:
[[0 2 3 3 3 1 2 2 1 1]
 [3 2 3 3 0 1 2 1 2 1]
 [3 0 2 3 3 1 2 2 1 1]
 [1 1 3 0 3 1 2 2 3 2]]

h(x):
 [0.875 1.125 1.25  1.375]
Nodes:
[[3 2 3 3 2 1 2 1 0 1]
 [0 3 2 3 3 1 2 2 1 1]
 [0 2 3 3 3 1 2 1 2 1]

G:\Github Repositories\Ring-Sorting-AI\air_berlin.py:63: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return np.array(actions)


In [ ]:
x = np.arange(16).reshape(4, 4)
print(x)
#np.take_along_axis(x, np.array([(1,0, 1, 0)]), axis=0)
ids = np.array([0, 1, 2, 3])

x[ids, range(4)]

In [ ]:
x[...,].shape

In [ ]:
# list gives you a view of rows
y = np.arange(16).reshape((4, 4))
list(y)[0][0] = 100
y

In [ ]:
y = np.arange(5)
list(y)[0] = 100
list(y)

In [ ]:
ls = [1, 2, 3]
ls.reverse()
ls