In [ ]:
import numpy as np
from air_berlin import *

%load_ext autoreload
%autoreload 2

In [8]:
n = 3
x = basic_solved_state(1, n)
x = shuffle_along_axis(x, 1)
xvals = get_xvals(x)
X = random_large_discs(n)
print(X)
print(x)

[4 1 4 2 2 4 2 4 1 2]
[[2 3 3 2 1 1 3 0 1 2]]


In [10]:
x = [[1, 1, 1, 2, 3, 0, 2, 2, 3, 3]]
d = x - np.roll(x, 1)
print(d < 0)

[[ True False False False False  True False False False False]]


In [ ]:
D = mod_difference_matrix(5)
print(D)

In [ ]:
X = np.array([1, 2, 3, 1, 2, 3, 4, 1, 2, 3])
x = np.array([[1, 2, 3, 1, 2, 3, 0, 1, 2, 3]])
xvals = get_xvals(x)

In [ ]:
#x = x[2:3]
xvals = xvals[2:3]

In [ ]:
x, xvals = expand(X, x, xvals)
print(x.shape)
print(X)
print(x)

In [ ]:
n = 4
m = n*n + 1
x = basic_solved_state(1, n)
x = shuffle_along_axis(x, 1)

In [ ]:
expanded = Expanded()

In [17]:
n = 3
x = basic_solved_state(N=1, n=n)
x = shuffle_along_axis(x, 1)
X = random_large_discs(n)

#n = 3
#x = np.array([[1, 1, 1, 3, 2, 2, 3, 3, 0, 2]], dtype=np.int8)
#X = np.array( [1, 2, 3, 4, 1, 2, 3, 1, 2, 3])

m = (n**2)
heuristic1 = SolvedHeuristic(n)
heuristic2 = PairwiseDistanceHeuristic(n, scale=1 / (n*n))
#heuristic = AdjacentDistanceHeuristic(n, 1)


print("Initial state:")
print("Large Disks:", X)
print("Small Disks:", x)

path = search(X, x, heuristic1, search_width=1, log_interval=1000, cost_scale=1)

#path = search(X, x, heuristic2, search_width=1, log_interval=1000, cost_scale=0)

#path = search(X, x, heuristic2, search_width=1, log_interval=1000, cost_scale=1)
#path = heuristic_search(X, x, heuristic, search_width=128, log_interval=5000)

Initial state:
Large Disks: [4 2 2 2 4 1 1 3 2 1]
Small Disks: [[2 2 2 1 1 0 3 1 3 3]]
Turn: 0, expanded: 0, fringe: 0, time elapsed: 0.0
Best g(x) + h(x) = 0 + 1.0
Turn: 1000, expanded: 757, fringe: 995, time elapsed: 0.19093751907348633
Best g(x) + h(x) = 8 + 1.0
Turn: 2000, expanded: 1430, fringe: 1741, time elapsed: 0.3458881378173828
Best g(x) + h(x) = 9 + 1.0
Turn: 3000, expanded: 2084, fringe: 2466, time elapsed: 0.5178334712982178
Best g(x) + h(x) = 10 + 1.0
Turn: 4000, expanded: 2648, fringe: 2915, time elapsed: 0.6567893028259277
Best g(x) + h(x) = 10 + 1.0
Turn: 5000, expanded: 3202, fringe: 3350, time elapsed: 0.8157382011413574
Best g(x) + h(x) = 11 + 1.0
Turn: 6000, expanded: 3772, fringe: 3862, time elapsed: 0.9896831512451172
Best g(x) + h(x) = 11 + 1.0
Turn: 7000, expanded: 4291, fringe: 4236, time elapsed: 1.1242437362670898
Best g(x) + h(x) = 11 + 1.0
Turn: 8000, expanded: 4780, fringe: 4528, time elapsed: 1.2602102756500244
Best g(x) + h(x) = 12 + 1.0
Turn: 9000, ex

In [18]:
print(path)

[[2 2 2 1 1 0 3 1 3 3]
 [2 2 2 1 1 3 0 1 3 3]
 [2 2 2 1 1 3 1 0 3 3]
 [2 2 2 1 1 3 1 3 0 3]
 [2 2 2 1 1 3 1 3 3 0]
 [0 2 2 1 1 3 1 3 3 2]
 [1 2 2 1 0 3 1 3 3 2]
 [1 2 2 0 1 3 1 3 3 2]
 [1 0 2 2 1 3 1 3 3 2]
 [1 2 2 2 1 3 1 3 3 0]
 [0 2 2 2 1 3 1 3 3 1]
 [1 2 2 2 0 3 1 3 3 1]
 [1 2 2 2 3 3 1 3 0 1]
 [1 2 2 2 3 3 0 3 1 1]
 [1 2 2 2 3 3 3 0 1 1]]


In [ ]:
from ipywidgets import interact

ring_plot = RingPlot(n, cmap="rainbow")

@interact(i=(0, path.shape[0]-1))
def show_path(i):
    ring_plot.show(path[i])

In [ ]:
name = "n25v1.npy"
out = np.array([X, path], dtype=np.object)
#np.save(f"solutions/{name}", out)

In [ ]:
name = "n15v1.npy"
load = np.load(f"solutions/{name}", allow_pickle=True)
X = load[0]
path = load[1]
n = int(np.sqrt(path.shape[1] - 1))

In [ ]:
# Test the Expanded class

from itertools import permutations

x = list(basic_solved_state(1, 3)[0])

normal_set = set()
expanded = Expanded()

iterations = 0
TP = 0
FP = 0
TN = 0
FN = 0

for p in permutations(x):
    iterations += 1
    
    x = np.array(p)[np.newaxis]
    
    if p in normal_set: 
        if expanded.contains(x)[0]:
            TN += 1
        else:
            FN += 1
    else:
        if not expanded.contains(x)[0]:
            TP += 1
        else:
            print(p)
            FP += 1
            
    normal_set.add(p)
    expanded.add(x)
    
    if iterations % 50000 == 0:
        print(f"iter={iterations} TN={TN}, FN={FN}, TP={TP}, FP={FP}")
        
    if iterations == 1000000:
        break


In [ ]:
import torch
import time
import numpy as np

x = torch.randperm(10000000)

t = time.time()
torch.sort(x)
cpu_time = time.time() - t

print("cpu time", cpu_time)

x = x.cuda()

t = time.time()
torch.sort(x)
gpu_time = time.time() - t
print("gpu time", gpu_time)

print(f"gpu is {round(cpu_time / gpu_time, 1)} times faster than cpu")