In [1]:
import numpy as np
from air_berlin import *
from visualizations import *
from search import *

%load_ext autoreload
%autoreload 2

In [36]:
n = 3
x = basic_solved_state(1, n)
x = shuffle_along_axis(x, 1)
xvals = get_xvals(x)
X = random_large_discs(n)
print(X)
print(x[0])

[3 3 4 3 2 1 2 3 3 3]
[3 3 1 2 0 2 2 1 1 3]


In [44]:
X = np.array([1, 2, 3, 1, 2, 3, 4, 1, 2, 3])
x = np.array([[1, 2, 3, 1, 2, 3, 0, 1, 2, 3]])
xvals = get_xvals(x)

In [48]:
#x = x[2:3]
xvals = xvals[2:3]

In [49]:
x, xvals = expand(X, x, xvals)
print(x.shape)
print(X)
print(x)

(2, 10)
[1 2 3 1 2 3 4 1 2 3]
[[2 0 3 1 2 3 1 1 2 3]
 [3 2 3 1 2 3 1 1 2 0]]


In [ ]:
n = 4
m = n*n + 1
x = basic_solved_state(1, n)
x = shuffle_along_axis(x, 1)

In [ ]:
expanded = Expanded()

In [ ]:
n = 15
x = basic_solved_state(N=1, n=n)
x = shuffle_along_axis(x, 1)
X = random_large_discs(n)

m = (n**2)
heuristic = YetAnotherAscendingDistanceHeuristic(n, scale=1 / (m - 1), weak_zero=True)

print("Initial state:")
print("Large Disks:", X)
print("Small Disks:", x)

#path = search(X, x, heuristic, search_width=16, log_interval=1000)
path = heuristic_search(X, x, heuristic, search_width=16, log_interval=1000)

In [34]:
ring_plot = RingPlot(n, cmap="rainbow")

In [35]:
from ipywidgets import interact

@interact(i=(0, path.shape[0]-1))
def show_path(i):
    ring_plot.show(path[i])

interactive(children=(IntSlider(value=10433, description='i', max=20867), Output()), _dom_classes=('widget-int…

In [ ]:
name = "n25v1.npy"
out = np.array([X, path], dtype=np.object)
#np.save(f"solutions/{name}", out)

In [32]:
name = "n15v1.npy"
load = np.load(f"solutions/{name}", allow_pickle=True)
X = load[0]
path = load[1]
n = int(np.sqrt(path.shape[1] - 1))

In [ ]:
# Test the Expanded class

from itertools import permutations

x = list(basic_solved_state(1, 3)[0])

normal_set = set()
expanded = Expanded()

iterations = 0
TP = 0
FP = 0
TN = 0
FN = 0

for p in permutations(x):
    iterations += 1
    
    x = np.array(p)[np.newaxis]
    
    if p in normal_set: 
        if expanded.contains(x)[0]:
            TN += 1
        else:
            FN += 1
    else:
        if not expanded.contains(x)[0]:
            TP += 1
        else:
            print(p)
            FP += 1
            
    normal_set.add(p)
    expanded.add(x)
    
    if iterations % 50000 == 0:
        print(f"iter={iterations} TN={TN}, FN={FN}, TP={TP}, FP={FP}")
        
    if iterations == 1000000:
        break


In [ ]:
import torch
import time
import numpy as np

x = torch.randperm(10000000)

t = time.time()
torch.sort(x)
cpu_time = time.time() - t

print("cpu time", cpu_time)

x = x.cuda()

t = time.time()
torch.sort(x)
gpu_time = time.time() - t
print("gpu time", gpu_time)

print(f"gpu is {round(cpu_time / gpu_time, 1)} times faster than cpu")